# Non-shared workflow that only runs on the github-actions-ci-cd module to automatically
# delete and re-release tags so that other modules can use something similar to carets (^)
# Caret (^) requirements are not supported by github-action e.g. @^2 does not work
# The action will tag v2 when 2.5.0 is released and v0.3 when 0.3.5 is released
# The new 'v' tag will point to the same sha  e.g. the sha of v2 will equal the sha of 2.5.0
# This allows modules to include workflows using the @v2 or @v0.3 syntax
# Using the 'v' prefix to avoid confusion with the '2' branch naming convention that Silverstripe uses

on:
  push:
    tags:
      - '*.*.*'

jobs:
  auto-tag:
    name: Auto-tag
    runs-on: ubuntu-latest
    steps:
      - name: Action tag
        run: |
          # refs/tags/0.1.23 => 0.1.23
          TAG=$(echo ${{ github.ref }} | cut -c 11-)
          if [[ $TAG =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            NEW_TAG="v${MAJOR}"
            if [ "$MAJOR" == "0" ]; then
              NEW_TAG=("v${MAJOR}.${MINOR}")
            fi
            # Delete old tag via GitHub API
            echo "Attempting to delete old $NEW_TAG tag (it may not exist yet)"
            curl -s \
            -X DELETE https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$NEW_TAG \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
            # Create new tag via GitHub API
            echo "Create new tag $NEW_TAG"
            curl -s \
            -X POST https://api.github.com/repos/${{ github.repository }}/git/refs \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d @- << EOF
            {
              "ref": "refs/tags/$NEW_TAG",
              "sha": "${{ github.sha }}"
            }
          EOF
          fi
